version: "3.8"

services:
  taiga-sampledata:
    image: taigaio/taiga-back:alpha
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
      TAIGA_PORT: 9000
    depends_on:
      - taiga-db
    entrypoint: bash -c "python manage.py sample_data"

  taiga-manage:
    image: taigaio/taiga-back:alpha
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
      TAIGA_PORT: 9000
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
