version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: taiga-db
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga-net

  taiga-back:
    image: taigaio/taiga-back:latest
    container_name: taiga-back
    environment:
      - TAIGA_SECRET_KEY=super-secret-key
      - TAIGA_DB_NAME=taiga
      - TAIGA_DB_USER=taiga
      - TAIGA_DB_PASSWORD=taiga
      - TAIGA_DB_HOST=postgres
      - TAIGA_URL=http://localhost:8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"  # exposed for direct access
    networks:
      - taiga-net

  taiga-front:
    image: taigaio/taiga-front-dist:latest
    container_name: taiga-front
    environment:
      - TAIGA_URL=http://localhost:8000
    ports:
      - "9000:80"  # access Taiga via http://localhost:9000
    networks:
      - taiga-net

volumes:
  taiga-db-data:

networks:
  taiga-net: