version: "3.8"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - db-data:/var/lib/postgresql/data

  taiga-back:
    image: taigaio/taiga-back:alpha
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
      POSTGRES_HOST: taiga-db
      TAIGA_PORT: 9000
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      # Get these in your profile https://github.com/settings/apps
      # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
      GITHUB_API_CLIENT_ID: "github-api-client-id"
      GITHUB_API_CLIENT_SECRET: "github-api-client-secret"
    volumes:
      - static-data:/taiga-back/static
      - media-data:/taiga-back/media
    depends_on:
      - taiga-db

  taiga-front:
    image: taigaio/taiga-front:alpha
    environment:
      TAIGA_PORT: 9000
      # Get these in your profile https://github.com/settings/apps
      # or in your organization profile https://github.com/organizations/{ORGANIZATION-SLUG}/settings/applications
      GITHUB_CLIENT_ID: "github-client-id"

  taiga-events:
    image: taigaio/taiga-events:alpha
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "taiga-back-secret-key"

  taiga-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - static-data:/taiga/static
      - media-data:/taiga/media
    depends_on:
      - taiga-back

volumes:
  static-data:
  media-data:
  db-data:
