version: "3.8"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - ./db-data:/var/lib/postgresql/data

  taiga-back:
    image: taigaio/taiga-back:alpha
    environment:
      DJANGO_SETTINGS_MODULE: "settings.config"
    volumes:
      - ./taiga-back/settings/config.py:/taiga-back/settings/config.py
      - static-data:/taiga-back/static
      - media-data:/taiga-back/media
    depends_on:
      - taiga-db

  taiga-front:
    image: taigaio/taiga-front:alpha
    volumes:
      - ./taiga-front/conf/conf.json:/usr/share/nginx/html/conf.json

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - static-data:/taiga/static
      - media-data:/taiga/media
    depends_on:
      - taiga-back

volumes:
  static-data:
  media-data:
