version: "3.8"

services:
  taiga-sampledata:
    image: taigaio/taiga-back:alpha
    environment:
      DJANGO_SETTINGS_MODULE: "settings.config"
    volumes:
      - ./taiga-back/settings/config.py:/taiga-back/settings/config.py
    depends_on:
      - taiga-db
    entrypoint: bash -c "python manage.py sample_data"

  taiga-manage:
    image: taigaio/taiga-back:alpha
    environment:
      DJANGO_SETTINGS_MODULE: "settings.config"
    volumes:
      - ./taiga-back/settings/config.py:/taiga-back/settings/config.py
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
