version: "3.8"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  taiga-back:
    image: taigaio/taiga-back:alpha
    environment:
      DJANGO_SETTINGS_MODULE: "settings.config"
    ports:
      - "8000:8000"
    volumes:
      - ./taiga-back/settings/config.py:/taiga-back/settings/config.py
      - ./static-data:/taiga-back/static
    depends_on:
      - taiga-db

  taiga-front:
    image: taigaio/taiga-front:alpha
    ports:
      - "9000:80"
    volumes:
      - ./taiga-front/conf/conf.json:/usr/share/nginx/html/conf.json
